version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db:postgres
    depends_on:
      - db
